language: python
python:
  - "2.7"

virtualenv:
    system_site_packages: true

# whitelist
branches:
  only:
    - dev
    - master

before_install:
    - echo "before_install"
    - echo $VIRTUAL_ENV
    - df -h
    - date
    - pwd
    - uname -a
    - python -V

script:
    - True